#ifndef MAIH_H
#define MAIN_H
 
int _putchar(char c);
int _islower(int c);
int _isalpha(int c);
int _abs(int n);
int _isupper(int c);
int _isdigit(int c);
int _strlen(char *s);
void _puts(char *s);
char *_strcpy(char *dest, char *src);
int _atoi(char *s);
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
int _strcmp(char *s1, char *s2);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(char *s, char c);
unsigned int _strspn(char *s, char *accept);
char *_strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
void print_alphabet(void);
void _puts_recursion(char *s);
void print_alphabet_x10(void);
int print_sign(int n);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
void positive_or_negative(int i);
int largest_number(int a, int b, int c);
int convert_day(int month, int day);
void print_remaining_days(int month, int day, int year);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
int string_length(char*);
void randomPasswordGeneration(int N);
void reverse_array(int *a, int n);
char *string_toupper(char *);
char *cap_string(char *);
char *cap_string(char *string);
char *leet(char *);
char *rot13(char *);
void print_number(int n);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
void print_buffer(char *b, int size);
void printASCII(char *b, int start, int end);
void printHexes(char *b, int start, int end);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _sqr_root(int n, int j);
char *string_toupper(char *string);
int compare(char *haystack, char *needle);
char *_strstr(char *haystack, char *needle);
int is_divisible(int num, int div);
int is_prime_number(int n);
char *leet(char *string);
void print_chessboard(char (*a)[8]);
int print_last_digit(int n);
void print_diagsums(int *a, int size);
int checker(char *s, int length, int a);
int is_palindrome(char *s);
void set_string(char **s, char *to);
int wildcmp(char *s1, char *s2);
int isPrintableASCII(int n);
void printHexes(char *b, int start, int end);
void printASCII(char *b, int start, int end);
void print_buffer(char *b, int size);

#endif